const PUBLISHERS = [
  "A \"Magic Wand\" Publication",
  "A ConCam Production",
  "A G Films Production",
  "A G-M Publication",
  "A Goodliffe Publication",
  "A Mark Leveridge Magic Publication",
  "A Martini's Magic Company Release",
  "A Salon de Magie Book, Ken Klosterman",
  "A Talon Publication",
  "A Top Magic Publication",
  "A-1 MagicalMedia",
  "A. M. Wilson, M. D.",
  "Aaron Fisher Magic",
  "Abbott's Magic",
  "Abraxas",
  "Ace Place Magic",
  "Agency of World Entertainment",
  "Al Mann Exclusives",
  "Aladdin's Magic Shop",
  "Alakazam",
  "Alan Sands Entertainment",
  "Alexander de Cova Productions",
  "Alta California Book and Job Printing House",
  "An Andi Gladwin Production",
  "Anthony Brahams",
  "Antinomy Magic",
  "Aplar Publishing",
  "Arcas Publications",
  "Arthur P. Felsman",
  "Astor",
  "avanT-Garde Magic",
  "B.S. Publications",
  "BammoMagic",
  "Beat & Roy Books",
  "Ben Harris Magic Publications",
  "Benchmark Magic Production",
  "Berland Presents",
  "BHM Industries / New Directions Publishing",
  "Binary Star Publications",
  "Blue Bikes Production",
  "Bob King Magic",
  "Bob Lynn",
  "Bob Lynn / Tony Raven",
  "Bodean Enterprises",
  "Borden Publishing Company",
  "Borwig & Horster",
  "Bradbury, Agnew & Co.",
  "Brunel White",
  "BW Magic Publishing",
  "C. Arthur Pearson Limited",
  "C.C. Éditions",
  "Caddy Manufacturing Company",
  "Calostro Publications",
  "Camirand Academy of Magic",
  "Card-Shark",
  "Carl Waring Jones",
  "Catman Publications",
  "Cecil E. Griffin",
  "CEDAM",
  "Chambers Magic Company",
  "Charles Scribner's Sons",
  "Charlsen + Johansen & Others",
  "Chas. C. Eastman",
  "ChicagoMagicBash Publications",
  "China Productions",
  "Chuck Martinez",
  "Clandestine Productions",
  "Cold Deck Company",
  "Coleccion Renglones",
  "Collectors' Workshop",
  "Columbia Magic Shop Inc.",
  "Conjuring Arts Research Center",
  "Conjurors' Library",
  "Conundrum Publishing",
  "Corinda's Magic Studio",
  "Crown Publishers, Inc.",
  "CYMYS",
  "D. Robbins & Co., Inc.",
  "Dan and Dave Industries, Inc.",
  "Daniel's Den Publication",
  "Danny Korem",
  "Dark Arts Press",
  "David Kemp & Company",
  "David Meyer Magic Books",
  "DeCovaMagic",
  "Developmental Productions Press",
  "dfgrd ediciones",
  "Divine Goddess 23 Productions",
  "DMB Publications",
  "Docc Co.",
  "Docc Hilford Productions",
  "Donald Holmes",
  "Donnybrook Enterprises, Inc.",
  "Dover Publications",
  "DTrik",
  "Dutton & Co.",
  "E. F. Rybolt",
  "East Coast Super Session",
  "Eckhard Böttchers Zauber-Butike",
  "Ed Mellon",
  "Ediciones El Espectador",
  "ediciones famulus",
  "ediciones Marré",
  "Ediciones Vernet Magic",
  "Edition Olms",
  "Editions Techniques du Spectacle",
  "Editorial El Caballo del Malo",
  "Editorial Frakson",
  "Edward Bagshawe & Co.",
  "El Duco",
  "Electro Fun",
  "Emerson & West",
  "Empire",
  "Every Trick in the Book Inc.",
  "Excelsior!! Productions",
  "F. G. Thayer",
  "Faber & Faber",
  "FASDIU Enterprises",
  "Fire Cat Studios",
  "Fleming Book Company",
  "Flora & Company",
  "Florence Art Edizioni",
  "FOCM Publication",
  "Fort Worth Magicians' Club",
  "Frank Werner",
  "Full Moon Magic Books",
  "Fun Inc.",
  "G & E Enterprises",
  "GBC Press",
  "Gene Gordon",
  "Genii",
  "Geo-Mar Publications",
  "George G. Harrap & Co., Ltd.",
  "George Snyder Jr",
  "George Starke",
  "Goldshadow Industries",
  "GrupoKaps",
  "Hermetic Press",
  "Guy Bavli - Perfect Magic",
  "I Saw That!",
  "Illuma - Illusion Management",
  "International Magic",
  "International Magic House",
  "Invisible Man Productions",
  "Invisible Practice Production",
  "Irv Weiner",
  "J A Enterprises",
  "Jahoda & Siegel",
  "Jeff Busby Magic, Inc.",
  "Jeff McBride, Inc.",
  "Jerry Mentzer (Magic Methods)",
  "John King - S. David Walker",
  "Jose's Studio",
  "Julius Sussmann, Hamburg",
  "Juris Druck + Verlag Zürich",
  "JustJoshinMagic",
  "Jörg Alexander ZauberKunst",
  "KANDA Publications",
  "Kanter's Magic Shop",
  "Kardyro-Torino Creations",
  "Kaufman and Company",
  "Kaufman and Greenberg",
  "Kee-West Productions",
  "Kennedy Enterprises",
  "Kerwin Benson Publishing",
  "Kreations & Trx",
  "L&L Publishing",
  "L. Davenport & Co.",
  "La boutique de l'illusion",
  "Laughing Room Only",
  "Lee Jacobs Productions",
  "Lehmann & Schüppel, Leipzig",
  "Lesclapart",
  "Levy & Müller",
  "Little, Brown and Company",
  "Louis Tannen",
  "Lybrary.com",
  "M. S. Messinger Printing",
  "M.C.M. Editora",
  "Magic Art Studio",
  "Magic by Boretti",
  "Magic City",
  "Magic Communication",
  "Magic House",
  "Magic Inspirations",
  "Magic Limited",
  "MAGIC Magazine",
  "Magic Methods",
  "Magic, Inc.",
  "Magical Publications",
  "Magicana",
  "Magick Enterprises",
  "Magicland, Tokyo",
  "Magico Magazine",
  "Magicseen Magazine",
  "Magicshop Vienna",
  "Magie",
  "Malbrough Magic",
  "Malek Enterprises",
  "ManusKrypt",
  "Marchand de Trucs",
  "Mark Wilson Publications",
  "Martin Breese",
  "Max Abrams",
  "Max Andrews (Vampire) LTD.",
  "Max Holden",
  "Mayette Magie Moderne",
  "Maynestream Productions",
  "Me and the other Guy Productions",
  "Media T Marketing",
  "Meir Yedid Magic",
  "Mephisto Huis",
  "Metempirical Magic",
  "Micky Hades",
  "Micky Hades Enterprises",
  "Micky Hades International",
  "Mike Caveney's Magic Words",
  "Mike Powers Magic",
  "Million Dollar Productions",
  "Mind Tapped Productions, LLC",
  "Miracle Makers",
  "Miracle Press",
  "Miracles Productions",
  "Montandon Magic",
  "Morissey Magic LTD.",
  "Murphy's Magic Supplies, Inc.",
  "Mystica",
  "MZvD",
  "Namlips Enterprises",
  "Nat Louis",
  "Necromancer Press",
  "Nelson & Nelson Ltd.",
  "Nelson Enterprises",
  "Neukomm & Zimmermann",
  "New Jinx Publication",
  "Nick Bolton",
  "Nightmare Alley Productions",
  "Obie O'Brien",
  "Ohmigosh Productions",
  "Old-Guy-In-The-Bathroom Productions",
  "Oliver Erens - œ",
  "Ortiz Publications",
  "Out of the Blue",
  "Owen Bros.",
  "Owen Magic Supreme",
  "Palooka Productions",
  "Paradigm Press",
  "Paraninfo",
  "Patrick Page Magic Limited",
  "Paul Diamond",
  "Pavel-Magic",
  "Penny's Publishing",
  "Penshaw Press",
  "PH Marketing Publication",
  "Philip R. Willmarth",
  "Piccadilly Books, Ltd",
  "Popular Magic Publications",
  "Princeton University Press",
  "Printed for T. Moore, London",
  "Private View",
  "Pro Print",
  "Producciones El Asombro, S.L.",
  "Professor Presto",
  "Psychic Entertainers Association",
  "Páginas",
  "R.O.P.S. Press",
  "Radio Free Atlantis Production",
  "Random House",
  "Rauscher & Cie AG",
  "Raw-Press",
  "Ray Gamble & W. Herbert Schuh",
  "Real Miracle Publication",
  "Red Silk Variety Productions",
  "Reed Swans Collective",
  "Reginald Scot Books",
  "Regow's House of Enchantment",
  "RFA Production",
  "Roche Magic Studio",
  "Rudolf Braunmüller",
  "Sacred Chao Productions",
  "San Francisco Book Company",
  "Sankey Magic",
  "Saturn Magic Ltd",
  "Savaco, Ltd.",
  "Scapegrace Press",
  "Schwabacher'sche Verlagsbuchhandlung",
  "Schweizerisches Jugendschriftenwerk Zürich",
  "Secrets of Dr. Dee",
  "Sedgehill Industries",
  "Selfpublished",
  "Silk King Studios",
  "simsalabonn",
  "Slydini Studio of Magic",
  "Smiling Mule Productions",
  "Sorcerer's Apprentice",
  "Sound of Magic",
  "Spade and Archer",
  "Sphinx Publishing Corporation",
  "Squash Publishing",
  "St. Pierre Enterprises",
  "Star Magic Co.",
  "Sterling Magic Company",
  "Steve Burton",
  "Steve Reynolds Magic",
  "Stevens Magic Emporium",
  "Syzygy Press",
  "Tannen Magic Inc.",
  "Taurus Magic Supply",
  "TCC",
  "Tenkai Prize Committee",
  "Tenyo",
  "Tesmar Zauberartikel",
  "The Cardician Press",
  "The Conjurors' Convention Corporation",
  "The Enchantment",
  "The False Deal (Mark Tams)",
  "The FM Factory",
  "The Genii Corporation",
  "The Impossible Co.",
  "The Ireland Magic Co.",
  "The Journal of Psience",
  "The Kee Publishing Co.",
  "The Kent & Surrey Press",
  "The London Magical Co.",
  "The Magic Apple",
  "The Magic Art Book Co.",
  "The Magic Circle",
  "The Magic Circle Foundation",
  "The Magic Corner",
  "The Magic Fun Factory",
  "the magic hands editions",
  "The Magic Wand Office",
  "The MasterMind Group",
  "The Merchant of Magic Ltd.",
  "The Miracle Factory",
  "The Neat Review",
  "The Presto Place",
  "The Second Deal (Jason Alford)",
  "The Secret Service",
  "The Sid Lorraine Hat & Rabbit Club",
  "The Supreme Magic Company",
  "The Tom-Foolery, Inc.",
  "The Usual Suspect",
  "The Welworth Company",
  "The Williamson Press, Inc.",
  "The Yogi Magic Mart",
  "Theory and Art of Magic Press",
  "Thinkers' Press",
  "Thomas van Büren Lenger",
  "Tokyodo Shuppan",
  "Trapdoor Productions",
  "Trik-Kard Specialties",
  "TVMagic.co.uk",
  "U. F. Grant",
  "Ultra Neat Ltd.",
  "Underground Collective",
  "Unikorn Magik",
  "Unique Magic Studio",
  "unknown publisher",
  "Vanishing Inc.",
  "Verlag Magischer Zirkel Hamburg",
  "Verlag Magischer Zirkel Leipzig",
  "Verlag O. Stolina",
  "W. H. Allen, London",
  "Weerd! Publishing",
  "Westbrook Publishing",
  "Wiener Spielkartenfabrik Fred. Piatnik & Söhne",
  "Will Goldston, Ltd.",
  "Wizard Publishing Company",
  "Wolfe Publishing Limited",
  "Wonder Workshop Berlin",
  "Wunderwinkel",
  "Zauberbuch-Verlag",
  "Zauberkabinett Shop",
  "Zauberkunst",
  "Zauberschrank",
  "Zauberzentrale München",
  "Zentralhaus für Kulturarbeit",
  "Édition Ch. Eggimann, Genève"
];

(function () {
  function injectPublishers() {
    const dl = document.getElementById('publisher-list');
    if (!dl || dl.dataset.loaded) return;
    const frag = document.createDocumentFragment();
    for (const p of PUBLISHERS) {
      const opt = document.createElement('option');
      opt.value = p;
      frag.appendChild(opt);
    }
    dl.appendChild(frag);
    dl.dataset.loaded = '1';
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', injectPublishers);
  } else {
    injectPublishers();
  }
})();
